# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "varnish-hit-stats"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jakub Pastuszek"]
  s.date = "2011-10-05"
  s.description = "Parsers and stat tools to analize Varnish ncsa logs"
  s.email = "jpastuszek@gmail.com"
  s.executables = ["varnish-hit-stats", "publish-varnish-hit-stats", "hit-stats-to-post"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/hit-stats-to-post",
    "bin/publish-varnish-hit-stats",
    "bin/varnish-hit-stats",
    "features/hit-stats-to-post.feature",
    "features/publish-varnish-hit-stats.feature",
    "features/step_definitions/jekyll_steps.rb",
    "features/step_definitions/script_and_file_staps.rb",
    "features/support/env.rb",
    "features/test_files/hit_stats1.csv",
    "features/test_files/test1.log",
    "features/varnish-hit-stats.feature",
    "lib/stat_counter.rb",
    "lib/varnish-hit-stats.rb",
    "site/.gitignore",
    "site/README.md",
    "site/Rakefile",
    "site/_config.yml",
    "site/_layouts/default.html",
    "site/_layouts/post.html",
    "site/_posts/.keep",
    "site/_sass/mixins/_syntax.scss",
    "site/_sass/screen.scss",
    "site/about.md",
    "site/atom.xml",
    "site/config.rb",
    "site/images/feed-icon.png",
    "site/index.html",
    "site/robots.txt",
    "site/sitemap.xml",
    "site/stylesheets/screen.css",
    "spec/spec_helper.rb",
    "spec/stat_counter_spec.rb",
    "spec/varnish-hit-stats_spec.rb"
  ]
  s.homepage = "http://github.com/jpastuszek/varnish-hit-stats"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "Tools for reporing Varnish stats"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<universal-access-log-parser>, [">= 0"])
      s.add_runtime_dependency(%q<jekyll>, ["~> 0.11.0"])
      s.add_runtime_dependency(%q<rdiscount>, ["~> 1.6.8"])
      s.add_runtime_dependency(%q<compass>, ["~> 0.11.5"])
      s.add_runtime_dependency(%q<posix-spawn>, ["~> 0.3.0"])
      s.add_runtime_dependency(%q<RedCloth>, ["~> 4.2.2"])
      s.add_runtime_dependency(%q<i18n>, [">= 0.5.0"])
      s.add_runtime_dependency(%q<activesupport>, ["~> 3.0.0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.6.0"])
      s.add_development_dependency(%q<cucumber>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<rake>, ["~> 0.9.2"])
    else
      s.add_dependency(%q<universal-access-log-parser>, [">= 0"])
      s.add_dependency(%q<jekyll>, ["~> 0.11.0"])
      s.add_dependency(%q<rdiscount>, ["~> 1.6.8"])
      s.add_dependency(%q<compass>, ["~> 0.11.5"])
      s.add_dependency(%q<posix-spawn>, ["~> 0.3.0"])
      s.add_dependency(%q<RedCloth>, ["~> 4.2.2"])
      s.add_dependency(%q<i18n>, [">= 0.5.0"])
      s.add_dependency(%q<activesupport>, ["~> 3.0.0"])
      s.add_dependency(%q<rspec>, ["~> 2.6.0"])
      s.add_dependency(%q<cucumber>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<rake>, ["~> 0.9.2"])
    end
  else
    s.add_dependency(%q<universal-access-log-parser>, [">= 0"])
    s.add_dependency(%q<jekyll>, ["~> 0.11.0"])
    s.add_dependency(%q<rdiscount>, ["~> 1.6.8"])
    s.add_dependency(%q<compass>, ["~> 0.11.5"])
    s.add_dependency(%q<posix-spawn>, ["~> 0.3.0"])
    s.add_dependency(%q<RedCloth>, ["~> 4.2.2"])
    s.add_dependency(%q<i18n>, [">= 0.5.0"])
    s.add_dependency(%q<activesupport>, ["~> 3.0.0"])
    s.add_dependency(%q<rspec>, ["~> 2.6.0"])
    s.add_dependency(%q<cucumber>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<rake>, ["~> 0.9.2"])
  end
end

