# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "varnish-hit-stats"
  s.version = "1.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jakub Pastuszek"]
  s.date = "2011-10-20"
  s.description = "Parsers and stat tools to analize Varnish ncsa logs"
  s.email = "jpastuszek@gmail.com"
  s.executables = ["vhs", "vhs-generate-posts", "vhs-process", "vhs-init", "vhs-publish"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "bin/vhs",
    "bin/vhs-generate-posts",
    "bin/vhs-init",
    "bin/vhs-process",
    "bin/vhs-publish",
    "features/.gitignore",
    "features/step_definitions/directory_steps.rb",
    "features/step_definitions/env_variable_steps.rb",
    "features/step_definitions/jekyll_steps.rb",
    "features/step_definitions/script_steps.rb",
    "features/support/env.rb",
    "features/test_files/hit_stats1.csv",
    "features/test_files/test1.log",
    "features/test_files/test1.yml",
    "features/test_files/test_empty.log",
    "features/test_files/test_empty.yml",
    "features/test_files/test_source/.gitignore",
    "features/test_files/test_source/README.md",
    "features/test_files/test_source/Rakefile",
    "features/test_files/test_source/_config.yml",
    "features/test_files/test_source/_layouts/default.html",
    "features/test_files/test_source/_layouts/post.html",
    "features/test_files/test_source/_sass/mixins/_syntax.scss",
    "features/test_files/test_source/_sass/screen.scss",
    "features/test_files/test_source/about.md",
    "features/test_files/test_source/atom.xml",
    "features/test_files/test_source/config.rb",
    "features/test_files/test_source/images/feed-icon.png",
    "features/test_files/test_source/index.html",
    "features/test_files/test_source/robots.txt",
    "features/test_files/test_source/sitemap.xml",
    "features/test_files/test_source/stylesheets/screen.css",
    "features/tmp/.keep",
    "features/vhs-generate-posts.feature",
    "features/vhs-init.feature",
    "features/vhs-process.feature",
    "features/vhs-publish.feature",
    "lib/hit_stats.rb",
    "lib/parser.rb",
    "lib/response_time_stats.rb",
    "lib/shell_script.rb",
    "lib/stat_counter.rb",
    "lib/table.rb",
    "site/.gitignore",
    "site/README.md",
    "site/Rakefile",
    "site/_config.yml",
    "site/_layouts/default.html",
    "site/_layouts/post.html",
    "site/_posts/.keep",
    "site/_sass/mixins/_syntax.scss",
    "site/_sass/screen.scss",
    "site/about.md",
    "site/atom.xml",
    "site/config.rb",
    "site/images/feed-icon.png",
    "site/index.html",
    "site/robots.txt",
    "site/sitemap.xml",
    "site/stylesheets/screen.css",
    "spec/hit_stats_spec.rb",
    "spec/response_time_stats_spec.rb",
    "spec/shell_script_spec.rb",
    "spec/spec_helper.rb",
    "spec/stat_counter_spec.rb",
    "spec/table_spec.rb",
    "varnish-hit-stats.gemspec"
  ]
  s.homepage = "http://github.com/jpastuszek/varnish-hit-stats"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "Tools for reporing Varnish stats"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<universal-access-log-parser>, ["~> 1.0.1"])
      s.add_runtime_dependency(%q<jekyll>, ["~> 0.11.0"])
      s.add_runtime_dependency(%q<rdiscount>, ["~> 1.6.8"])
      s.add_runtime_dependency(%q<compass>, ["~> 0.11.5"])
      s.add_runtime_dependency(%q<posix-spawn>, ["~> 0.3.0"])
      s.add_runtime_dependency(%q<RedCloth>, ["~> 4.2.2"])
      s.add_runtime_dependency(%q<i18n>, [">= 0.5.0"])
      s.add_runtime_dependency(%q<activesupport>, ["~> 3.0.0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.6.0"])
      s.add_development_dependency(%q<cucumber>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<rake>, ["~> 0.9.2"])
    else
      s.add_dependency(%q<universal-access-log-parser>, ["~> 1.0.1"])
      s.add_dependency(%q<jekyll>, ["~> 0.11.0"])
      s.add_dependency(%q<rdiscount>, ["~> 1.6.8"])
      s.add_dependency(%q<compass>, ["~> 0.11.5"])
      s.add_dependency(%q<posix-spawn>, ["~> 0.3.0"])
      s.add_dependency(%q<RedCloth>, ["~> 4.2.2"])
      s.add_dependency(%q<i18n>, [">= 0.5.0"])
      s.add_dependency(%q<activesupport>, ["~> 3.0.0"])
      s.add_dependency(%q<rspec>, ["~> 2.6.0"])
      s.add_dependency(%q<cucumber>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<rake>, ["~> 0.9.2"])
    end
  else
    s.add_dependency(%q<universal-access-log-parser>, ["~> 1.0.1"])
    s.add_dependency(%q<jekyll>, ["~> 0.11.0"])
    s.add_dependency(%q<rdiscount>, ["~> 1.6.8"])
    s.add_dependency(%q<compass>, ["~> 0.11.5"])
    s.add_dependency(%q<posix-spawn>, ["~> 0.3.0"])
    s.add_dependency(%q<RedCloth>, ["~> 4.2.2"])
    s.add_dependency(%q<i18n>, [">= 0.5.0"])
    s.add_dependency(%q<activesupport>, ["~> 3.0.0"])
    s.add_dependency(%q<rspec>, ["~> 2.6.0"])
    s.add_dependency(%q<cucumber>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<rake>, ["~> 0.9.2"])
  end
end

